### ISSUE TITLE
XSS via javascript: scheme

### ISSUE THREAD

**Issue by caioluders** [pieromqwerty/url-lengthener#2]
Hey, 
The software is vulnerable to XSS if you provide a `javascript:` scheme. Maybe you want to stick with http/https only.

`javascript:alert(document.domain)`

https://aaa.aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa.com/a?áaaÂáaaÂáaaÂáaaÂáaaÂáaaÂáaaÂáaaÂáaaÂáaaÂáaaÂáaaÂáaaÂáaaÂáaaÂáaaÂáaaÂáaaÂáaaÂáaaÂáaaÂáaaÂáaaÂáaaÂáaaÂáaaÂáaaÂáaaÂáaaÂáaaÂáaaÂáaaÂáaaÂáaaÂåÁåàæååàæâåâæáåÀæaæãâÁåàåÃåäæáæãáAåãåÆåâæäåÄåäåÅæãáÅåãåÆåÄåàåÀåÅáÀ

https://owasp.org/www-community/attacks/xss/

**Comment by piemadd** [comment]
Fun thing that you found that, since I was actually working on a fix
already. Greatly appreciated thought!

**Comment by piemadd** [comment]
Fixed in 1.4.2, thanks for the report!
