### ISSUE TITLE
API broken?

### ISSUE THREAD

**Issue by nwithan8** [pieromqwerty/url-lengthener#3]
Was creating a Python package for A(x56) (https://github.com/nwithan8/ax56) and could not get the API to work. It keeps redirecting to the landing page.

**Comment by piemadd** [comment]
Hm, you're sending the GET request to /a?url="url here" right?

**Comment by piemadd** [comment]
Fixed it! Turns out the order you put routes on express.js matter? Tested with the library as well: 
![image](https://user-images.githubusercontent.com/22846928/118385424-9d371f00-b5dc-11eb-83c9-317c3426ec5f.png)
