### ISSUE TITLE
Website doesn't work

### ISSUE THREAD

**Issue by TheTechRobo** [pieromqwerty/url-lengthener#9]
Stuck on redirecting

**Comment by piemadd** [comment]
that generally means some sort of error was encountered. what was the link you were sent?

**Comment by TheTechRobo** [comment]
it happens on every link i try.

the issue is on firefox 78.13.0 esr, fwiw.

is there a known incompatibility with this version?

**Comment by TheTechRobo** [comment]
the console just says "-1".

example link: https://aaa.aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa.com/a?%C3%A1aa%C3%82%C3%A1aa%C3%82%C3%A1aa%C3%82%C3%A1aa%C3%82%C3%A1aa%C3%82%C3%A1aa%C3%82%C3%A1aa%C3%82%C3%A1aa%C3%82%C3%A1aa%C3%82%C3%A1aa%C3%82%C3%A1aa%C3%82%C3%A1aa%C3%82%C3%A1aa%C3%82%C3%A1aa%C3%82%C3%A1aa%C3%82%C3%A1aa%C3%82%C3%A1aa%C3%82%C3%A1aa%C3%82%C3%A1aa%C3%82%C3%A1aa%C3%82%C3%A1aa%C3%82%C3%A1aa%C3%82%C3%A1aa%C3%82%C3%A1aa%C3%82%C3%A1aa%C3%82%C3%A1aa%C3%82%C3%A1aa%C3%82%C3%A1aa%C3%82%C3%A1aa%C3%82%C3%A1aa%C3%82%C3%A1aa%C3%82%C3%A1aa%C3%82%C3%A1aa%C3%82%C3%A1aa%C3%82%C3%A1aa%C3%82%C3%A1aa%C3%82%C3%A1aa%C3%82%C3%A1aa%C3%82%C3%A1aa%C3%82%C3%A1aa%C3%82%C3%A1aa%C3%82%C3%A1aa%C3%82%C3%A5A%C3%A6%C3%A3%C3%A6%C3%A3%C3%A6a%C3%A6%C3%A2%C3%A2%C3%81%C3%A1%C3%86%C3%A1%C3%86%C3%A5A%C3%A5%C3%A4%C3%A5%C3%83%C3%A5%C3%83%C3%A5%C3%86%C3%A1%C3%85%C3%A5%C3%A2%C3%A5%C3%A0

**Comment by piemadd** [comment]
It works for me? Weird hmmmm

**Comment by piemadd** [comment]
Try this link maybe? [https://aaa.aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa.com/a?áaaÂáaaÂáaaÂáaaÂáaaÂáaaÂáaaÂáaaÂáaaÂáaaÂáaaÂáaaÂáaaÂáaaÂáaaÂáaaÂáaaÂáaaÂáaaÂáaaÂáaaÂáaaÂáaaÂáaaÂáaaÂáaaÂáaaÂáaaÂáaaÂáaaÂáaaÂáaaÂáaaÂáaaÂáaaÂáaaÂáaaÂáaaÂáaaÂáaaÂáaaÂáaaÂåAæãæãæaæââÁáÆáÆåAåäåÃåÃåÆáÅåâåà](https://aaa.aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa.com/a?áaaÂáaaÂáaaÂáaaÂáaaÂáaaÂáaaÂáaaÂáaaÂáaaÂáaaÂáaaÂáaaÂáaaÂáaaÂáaaÂáaaÂáaaÂáaaÂáaaÂáaaÂáaaÂáaaÂáaaÂáaaÂáaaÂáaaÂáaaÂáaaÂáaaÂáaaÂáaaÂáaaÂáaaÂáaaÂáaaÂáaaÂáaaÂáaaÂáaaÂáaaÂáaaÂåAæãæãæaæââÁáÆáÆåAåäåÃåÃåÆáÅåâåà)

**Comment by TheTechRobo** [comment]
I think it's an issue with firefox esr 78.13.0, as me on FF Developer Edition (92.something) works fine with both links.

**Comment by piemadd** [comment]
I dont think thats the case as its worked on 78 in the past. IG ill
download it and see whats wrong.

**Comment by piemadd** [comment]
Seems to work for me now in FF, can you confirm?

**Comment by TheTechRobo** [comment]
Sorry for the delay. I'll finally stop being lazy and test this :P

**Comment by TheTechRobo** [comment]
Still happens - 78.15.0.

The console shows it's coming from line 10 in redirect.js (the console.log call). But I doubt that's the underlying issue. (Maybe it is tho)

Nothing else shows up though. Is this just my system???

**Comment by piemadd** [comment]
What is the URL?

**Comment by TheTechRobo** [comment]
I tried entering both http://google.com and http://hello.ca into the site.

**Comment by piemadd** [comment]
this makes no sense. send a ss of what the console poops out ig?

**Comment by piemadd** [comment]
also im starting to feel like this is something with your system, but that makes absolutely no sense. do you have any strict privacy settings?

**Comment by TheTechRobo** [comment]
Hmmm... I might.

Sorry for not being able to respond well, the computer in question is difficult to access and I don't have another 78 ESR install.

**Comment by piemadd** [comment]
i see i see. take your time!

**Comment by TheTechRobo** [comment]
Standard privacy settings. I'm really confused.

I'll send an SS in a few

**Comment by TheTechRobo** [comment]
![image](https://user-images.githubusercontent.com/52163910/145681318-db5d4195-edd1-4346-8eef-872ae105091b.png)

**Comment by piemadd** [comment]
this is so fucking weird...

**Comment by piemadd** [comment]
Ok I've made it console.log url stuff. Crossing my finger that it is just some weird decoding issue.

**Comment by TheTechRobo** [comment]
```
-1
 � � � � � � � � � � � � � � � � � � � � � � � � � � � � � � � � � � � � � � � � �https://google.com 
 � � � � � � � � � � � � � � � � � � � � � � � � � � � � � � � � � � � � � � � � �https://google.com
```

so yeah... probably a decoding problem

**Comment by piemadd** [comment]
oh thats sus

**Comment by piemadd** [comment]
the thing is, that unicode character just shouldn't exist. i am absolutely baffled as to why like 30 of them are being appended onto the beginning of the URL

**Comment by TheTechRobo** [comment]
Yeah, it's...really weird.

**Comment by TheTechRobo** [comment]
Well, I just found a revelation. 1 sec while I type it.

**Comment by TheTechRobo** [comment]
Basically, those chars show up **even on my Chromebook where it works**.
If I open the console, load the lengthened URL, and stop the page loading, **I still see those chars in console**

Perhaps modern browsers can handle those chars in the redirect but FF 78 just... can't?
Or maybe the console.log is messed up?

https://user-images.githubusercontent.com/52163910/146972333-92c3a5d3-b58d-4f6e-bd42-d6abad8c6b0a.mp4

**Comment by piemadd** [comment]
ok i finally have an update for you! i finally switched the system over to handling redirects on the server side so that should fix any issues previously had!

**Comment by TheTechRobo** [comment]
works! thanks! still confused as to what the issue was, I guess we'll never know.

**Comment by piemadd** [comment]
my best guess is escape characters, good to close this!
